version: '2'
services:
  broken-transmitter:
    build: ./flask
    restart: always

  nginx:
    image: nginx
    depends_on:
      - broken-transmitter
    ports:
      - "127.0.0.1:30003:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
